version: "3.8"

services:
    mysql-db:
        image: mysql
        container_name: mysql-db
        environment:
            - MYSQL_DATABASE=${TYPEORM_DATABASE:-laravel_react}
            - MYSQL_PASSWORD=${TYPEORM_PASSWORD:-secret}
            - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD:-secret}
        ports:
            - ${DB_PORT:-13308}:3306
        command: --default-authentication-plugin=mysql_native_password
volumes:
    db-store:
        driver: local
